### ISSUE TITLE
Build error: use of undeclared identifier 'VerifyOffset'

### ISSUE THREAD

**Issue by alculquicondor** [google/fplbase#5]
There are several calls to this function.

```
In file included from /home/alculquicondor/Projects/fplbase/src/asset_manager.cpp:21:                              
jni/../gen/include/mesh_generated.h:113:12: error: use of undeclared identifier 'VerifyOffset'                     
           VerifyOffset(verifier, VT_INDICES) &&                                                                   
           ^                                    
```

Maybe I'm missing some environmental variable?

**Comment by alculquicondor** [comment]
I was on tag v1.0.0
master mostly works, except for the need to be on google/mathfu@f05953d8a46be941cdaba2c5f9a8e514eafc6f5c which depends on scoopr/vectorial

Also, I had to set the following variables:

```
DEPENDENCIES_DIR=$(pwd)/dependencies
export DEPENDENCIES_FLATBUFFERS_DIR=$DEPENDENCIES_DIR/flatbuffers
export DEPENDENCIES_FPLUTIL_DIR=$DEPENDENCIES_DIR/fplutil
export DEPENDENCIES_WEBP_DIR=$DEPENDENCIES_DIR/webp
export DEPENDENCIES_STB_DIR=$DEPENDENCIES_DIR/stb
export DEPENDENCIES_SDL_DIR=$DEPENDENCIES_DIR/sdl
export DEPENDENCIES_MATHFU_DIR=$DEPENDENCIES_DIR/mathfu
export DEPENDENCIES_VECTORIAL_DIR=$DEPENDENCIES_DIR/mathfu/dependencies/vectorial
```

**Comment by aardappel** [comment]
That sounds like whatever version you're compiling is depending on an older version of FlatBuffers (or rather, the schemas in FPLBase were generated with a newer version of FlatBuffers than the FlatBuffers dependency). @haroonq ?

**Comment by haroonq** [comment]
Tag 1.0.0 is from Feb 23, so I'm not sure what's going on there. 

I've only done a single push of fplbase (24cb8863) last month which depends on flatbuffers @ 7fe2812 which includes the VerifyOffset function.
